services:
  #Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.3
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: 147.45.219.199
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres-keycloak

  # PostgreSQL для Keycloak
  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data

  # PostgreSQL для Spring Boot
  postgres-forum:
    container_name: postgres-forum
    image: postgres:15
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: forum
      POSTGRES_PASSWORD: forum
    ports:
      - "5434:5432"
    volumes:
      - postgres_forum_data:/var/lib/postgresql/data

  # Spring Boot backend
  springboot-backend:
    build:
      context: ./forum-back
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-forum:5432/forum
      SPRING_DATASOURCE_USERNAME: forum
      SPRING_DATASOURCE_PASSWORD: forum
      KEYCLOAK_URL: http://147.45.219.199:8080
    depends_on:
      - postgres-forum

  # React frontend
  react-frontend:
    build:
      context: ./forum-front/my-app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://147.45.219.199:8081
      REACT_APP_KEYCLOAK_URL: http://147.45.219.199:8080
    depends_on:
      - springboot-backend

volumes:
  postgres_keycloak_data:
  postgres_forum_data: